packages:
  - apps/*

catalogs:
  common:
    "@nestjs/common": ^11.0.1
    "@nestjs/core": ^11.0.1
    "@nestjs/platform-express": ^11.0.1
    "reflect-metadata": ^0.2.2
    "rxjs": ^7.8.1
    "axios": ^1.9.0
    "@eslint/eslintrc": ^3.2.0
    "@eslint/js": ^9.18.0
    "@nestjs/cli": ^11.0.0
    "@nestjs/schematics": ^11.0.0
    "@nestjs/testing": ^11.0.1
    "@swc/cli": ^0.6.0
    "@swc/core": ^1.10.7
    "@types/express": ^5.0.0
    "@types/jest": ^29.5.14
    "@types/node": ^22.10.7
    "@types/supertest": ^6.0.2
    "eslint": ^9.18.0
    "eslint-config-prettier": ^10.0.1
    "eslint-plugin-prettier": ^5.2.2
    "globals": ^16.0.0
    "jest": ^29.7.0
    "prettier": ^3.4.2
    "source-map-support": ^0.5.21
    "supertest": ^7.0.0
    "ts-jest": ^29.2.5
    "ts-loader": ^9.5.2
    "ts-node": ^10.9.2
    "tsconfig-paths": ^4.2.0
    "typescript": ^5.7.3
    "typescript-eslint": ^8.20.0

overrides:
  "axios": 1.7.4
  "async": 3.2.2
  "node-fetch": 2.6.11
  "cross-spawn": 7.0.5
  "body-parser": 1.20.3
  "ip": 2.0.1
  "@types/express-serve-static-core": 4.17.37
  "minimist": 1.2.6
  "babel-loader": 9.1.3
  "parse-url": 6.0.1
  "@babel/traverse": 7.25.3
  "decode-uri-component": 0.2.2
  "moment": 2.29.4
  "parse-path": 5.0.0
  "react": 18.2.0
  "react-dom": 18.2.0
  "plist": 3.0.4
  "fast-xml-parser": 4.2.4
  "@react-native/js-polyfills": 0.74.84
  "@xmldom/xmldom": 0.8.7
  "markdown-it": 13.0.2

linkWorkspacePackages: deep
injectWorkspacePackages: true